name: CTFTime Update to Discord Webhook
author: DarkGuy10
description: GitHub Action for sending CTFTime updates to discord webhook

inputs:
  github_token:
    description: GitHub authentication token
    required: true
  webhook_url:
    description: The Webhook URL
    required: true
  window_size:
    description: Size of fetch window
    required: true

runs:
  using: node20
  main: dist/index.js

branding:
  icon: upload-cloud
  color: blue
